version: '3.3'
services:
  gadgets:
    image: amazoncorretto:17
    networks:
    - network_apis
    volumes:
    - ./apps:/apps
    ports:
    - 8080:8080
    environment:
      MYSQL_HOST: db
    command:
    - java
    - -jar
    - /apps/GadgetAPI.jar
    depends_on:
    - gadgets_db
    links:
    - gadgets_db:db
    restart: always
  videojuegos:
    image: amazoncorretto:17
    networks:
    - network_apis
    volumes:
    - ./apps:/apps
    ports:
    - 8081:8081
    environment:
      MYSQL_HOST: db
    command:
    - java
    - -jar
    - /apps/VideojuegosAPI.jar
    depends_on:
    - videojuegos_db
    links:
    - videojuegos_db:db
    restart: always
  gadgets_db:
    image: mariadb
    networks:
      - network_apis
    environment:
      MARIADB_ROOT_PASSWORD: 123456
    volumes:
    - ./apps/gadgets:/docker-entrypoint-initdb.d
    - ./apps/gadgets/data:/var/lib/mysql
  videojuegos_db:
    image: mariadb
    networks:
      - network_apis
    environment:
      MARIADB_ROOT_PASSWORD: 123456
    volumes:
    - ./apps/videojuegos:/docker-entrypoint-initdb.d
    - ./apps/videojuegos/data:/var/lib/mysql
networks:
  network_apis: